version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: felipe_lemos
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./server-ts
    command: npm run dev
    volumes:
      - ./server-ts:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/felipe_lemos
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: ./client
    command: npm run dev -- --host
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:3001

volumes:
  pgdata:
