name: Build & Deploy Backend (Docker -> Docker Hub -> DigitalOcean App)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./server-ts
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/felipe-lemos-api:latest

      - name: Trigger DigitalOcean App Deploy via API
        if: ${{ secrets.DO_API_TOKEN != '' }}
        env:
          DO_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          curl -X POST "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments"             -H "Content-Type: application/json"             -H "Authorization: Bearer $DO_TOKEN"             -d '{}'
